<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

class WorkshopInscriptionCreatedAdmin extends Mailable
{
    use Queueable, SerializesModels;

    public array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: 'Nova inscripció al taller - '.$this->data['workshop_name'],
        );
    }

    public function content(): Content
    {
        return new Content(
            view: 'mail.workshop-inscription-created-admin',
            with: ['data' => $this->data],
        );
    }

   
    public function attachments(): array
    {
        return [];
    }
}
