name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
  workflow_dispatch:

env:
  PHP_VERSION: '8.5'
  NODE_VERSION: '22'

jobs:
  laravel-pint-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer
      - name: Install Laravel Pint
        run: composer global require laravel/pint
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install
      - name: Run Pint
        run: pint
      - name: Format Frontend
        run: npm run format
      - name: Lint Frontend
        run: npm run lint --fix
      - name: Configure Git credentials
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
      - name: Push Changes Back to Repo Manually
        run: |
          git config user.name "brandonalcantara17"
          git config user.email "brandonalcantara@proton.me"
          git add .
          git commit -m "Laravel Pint" || exit 0
          git push

  tests:
    runs-on: ubuntu-latest
    needs: laravel-pint-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2
          coverage: xdebug
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Node Dependencies
        run: npm i
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Copy Environment File
        run: cp .env.example .env
      - name: Configure Test Database
        run: |
          sed -i "s/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/g" .env
          echo "DB_DATABASE=:memory:" >> .env
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Build Assets
        run: npm run build
      - name: Tests
        run: php artisan test
